mall/mall/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("user.urls", namespace='user')),
	url(r"^goods/", include("goods.urls", namespace="goods")),
	url(r"^stores/", include("stores.urls", namespace="stores")),
	url(r"^$", include("common.urls", namespace="common")),
]

mall/stores/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	# 增加店铺
	url(r"^add/$", views.add, name="add"),
	# 查询店铺
	url(r"^list/$", views.list, name="list"),
	# 修改店铺
	url(r"^(?P<s_id>\d+)/update/$", views.update, name="update"),
	# 店铺详情
	url(r"^(?P<s_id>\d+)/detail/$", views.detail, name="detail"),
	# 关闭店铺
	url(r"^(?P<s_id>\d+)/(?P<status>\d+)/change/$", views.change, name="change"),
]

mall/stores/models.py
from django.db import models

from django.contrib.auth.models import User


class Stores(models.Model):
	id = models.AutoField(primary_key=True)
	# 店铺名称
	name = models.CharField(max_length=255, unique=True, verbose_name="店铺名称")
	# 店铺封面
	cover = models.ImageField(upload_to="sataic/stores/store", default="sataic/stores/store/3.jpg", verbose_name="店铺封面")
	# 店铺描述
	intro = models.TextField(verbose_name="店铺描述")
	# 开店时间
	openTime = models.DateTimeField(auto_now_add=True, verbose_name="开店时间")
	#店铺状态
	status = models.IntegerField(default=0, verbose_name="店铺状态")
	#店主
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="店主")

mall/stores/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET

from . import models
from goods.models import GoodsType


#增加店铺
@login_required()
def add(request):
	if request.method == "GET":
		return render(request, "stores/add.html", {})
	else:
		name = request.POST["name"].strip()
		intro = request.POST["intro"].strip()

		try:
			cover = request.FILES["cover"]
			store = models.Stores(name=name, intro=intro, cover=cover, user=request.user)
		except:
			store = models.Stores(name=name, intro=intro, user=request.user)
		store.save()

		return redirect(reverse("stores:detail", kwargs={"s_id": store.id}))


#查询店铺
@require_GET
@login_required()
def list(request):
	stores = models.Stores.objects.filter(user=request.user, status__in=[0, 1])
	return render(request, "stores/list.html", {"stores": stores})


#修改店铺
@login_required()
def update(request, s_id):
	if request.method == "GET":
		store = models.Stores.objects.get(pk=s_id)
		return render(request, "stores/update.html", {"store":store})
	else:
		name = request.POST["name"].strip()
		intro = request.POST["intro"].strip()

		store = models.Stores.objects.get(pk=s_id)
		store.name = name
		store.intro = intro
		try:
			cover = request.FILES["cover"]
			store.cover = cover
		except:
			pass
		store.save()

		return redirect(reverse("stores:detail", kwargs={"s_id": store.id}))



#店铺详情
@require_GET
@login_required()
def detail(request, s_id):
	store = models.Stores.objects.get(pk=s_id)
	# type1 = GoodsType.objects.filter(parent__isnull=True)
	return render(request, "stores/detail.html", {"store": store})#, "type1":type1})


#关闭店铺
@require_GET
@login_required()
def change(request, s_id, status):
	store = models.Stores.objects.get(pk=s_id)
	store.status = int(status)
	store.save()
	if store == 2:
		return redirect(reverse("stores:list"))
	else:
		return render(request, "stores/detail.html", {"store": store})

mall/stores/templates/stores/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>开业大吉</title>
</head>
<body>
    <h1>开业大吉</h1>
    <form action="{% url 'stores:add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        店铺名称：<input type="text" name="name"> <br>
        店铺封面：<input type="file" name="cover" id="cover"> <br>
        店铺介绍 <textarea name="intro" id="intro" cols="30" rows="10"></textarea> <br>
        <input type="submit" value="开业大吉">
    </form>
</body>
</html>

mall/stores/templates/stores/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>店铺详情页面</title>
</head>
<body>
    <h1>店铺详情页面</h1>
    <table border="1">
        <tr>
            <td>店铺头像</td>
            <td><img src="/{{store.cover}}" alt="头像"></td>
        </tr>
        <tr>
            <td>店铺名称</td>
            <td>{{store.name}}</td>
        </tr>
        <tr>
            <td>店铺介绍</td>
            <td>{{store.intro}}</td>
        </tr>
        <tr>
            <td>店铺状态</td>
            <td>
                {% if store.status == 0 %}
                    <p>正在营业</p>
                    <a href="{% url 'stores:change' store.id 1 %}">暂停营业</a>
                    <a href="{% url 'stores:change' store.id 2 %}">删除店铺</a>
                {% elif store.status == 1 %}
                    <p>暂停营业</p>
                    <a href="{% url 'stores:change' store.id 0 %}">开始营业</a>
                    <a href="{% url 'stores:change' store.id 2 %}">删除店铺</a>
                {% elif store.status == 2 %}
                    <p>店铺已经被删除，请联系管理员</p>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>操作</td>
            <td><a href="{% url 'stores:update' store.id %}">修改店铺信息</a></td>
        </tr>
    </table>
    <hr>
    <!--<h1>上架商品</h1>-->
    <!--<form action="#" method="post" >-->
        <!--{% csrf_token %}-->
        <!--商品名称：<input type="text" name="name" id="name"> <br>-->
        <!--商品单价：<input type="number" name="price"> <br>-->
        <!--商品库存：<input type="number" name="stock"> <br>-->
        <!--<input type="hidden" name="store" value="{{store.id}}"> <br>-->
        <!--商品图片：<input type="file" name="cover"><button>继续添加</button> <br>-->
        <!--商品类型：-->
            <!--<select name="type1" id="type1">-->
                <!--<option value="-1">请选择一级类型</option>-->
                <!--{% for t in type1 %}-->
                <!--<option value="{{t.id}}">{{t.name}}</option>-->
                <!--{% endfor %}-->
            <!--</select>-->
            <!--<select name="type2" id="type2">-->
                <!--{% for t in type2 %}-->
                <!--<option value="{{t.id}}">{{t.name}}</option>-->
                <!--{% endfor %}-->
            <!--</select>-->
        <!--商品介绍：<textarea name="intro" id="intro" cols="30" rows="10"></textarea> <br>-->
    <!--</form>-->
</body>
</html>

mall/stores/templates/stores/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看自己的所有的店铺</title>
</head>
<body>
    <h1>查看自己的所有的店铺</h1>
    <table border="1">
        {% for store in stores %}
        <tr>
            <td>店铺头像</td>
            <td><img src="/{{store.cover}}" alt="店铺头像"></td>
        </tr>
        <tr>
            <td>店铺名称</td>
            <td>{{store.name}}</td>
        </tr>
        <tr>
            <td>店铺介绍</td>
            <td>{{store.intro}}</td>
        </tr>
        <tr>
            <td><a href="{% url 'stores:detail' store.id %}">查询详情</a></td>
        </tr>
        {% empty %}
        <tr>
            <td>没有查询到您的店铺，快去<a href="{% url 'stores:add' %}">开店</a>吧</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

mall/stores/templates/stores/list1.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <meta name="author" content="order by dede58.com"/>
		<title>小米手机列表</title>
		<link rel="stylesheet" type="text/css" href="./css/style.css">
	</head>
	<body>
	<!-- start header -->
		<header>
			<div class="top center">
				<div class="left fl">
					<ul>
						<li><a href="http://www.mi.com/" target="_blank">小米商城</a></li>
						<li>|</li>
						<li><a href="">MIUI</a></li>
						<li>|</li>
						<li><a href="">米聊</a></li>
						<li>|</li>
						<li><a href="">游戏</a></li>
						<li>|</li>
						<li><a href="">多看阅读</a></li>
						<li>|</li>
						<li><a href="">云服务</a></li>
						<li>|</li>
						<li><a href="">金融</a></li>
						<li>|</li>
						<li><a href="">小米商城移动版</a></li>
						<li>|</li>
						<li><a href="">问题反馈</a></li>
						<li>|</li>
						<li><a href="">Select Region</a></li>
						<div class="clear"></div>
					</ul>
				</div>
				<div class="right fr">
					<div class="gouwuche fr"><a href="">购物车</a></div>
					<div class="fr">
						<ul>
							<li><a href="./login.html" target="_blank">登录</a></li>
							<li>|</li>
							<li><a href="./register.html" target="_blank" >注册</a></li>
							<li>|</li>
							<li><a href="">消息通知</a></li>
						</ul>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</header>
	<!--end header -->

<!-- start banner_x -->
		<div class="banner_x center">
			<a href="./index.html" target="_blank"><div class="logo fl"></div></a>
			<a href=""><div class="ad_top fl"></div></a>
			<div class="nav fl">
				<ul>
					<li><a href="">小米手机</a></li>
					<li><a href="">红米</a></li>
					<li><a href="">平板·笔记本</a></li>
					<li><a href="">电视</a></li>
					<li><a href="">盒子·影音</a></li>
					<li><a href="">路由器</a></li>
					<li><a href="">智能硬件</a></li>
					<li><a href="">服务</a></li>
					<li><a href="">社区</a></li>
				</ul>
			</div>
			<div class="search fr">
				<form action="" method="post">
					<div class="text fl">
						<input type="text" class="shuru"  placeholder="小米6&nbsp;小米MIX现货">
					</div>
					<div class="submit fl">
						<input type="submit" class="sousuo" value="搜索"/>
					</div>
					<div class="clear"></div>
				</form>
				<div class="clear"></div>
			</div>
		</div>
<!-- end banner_x -->

	<!-- start banner_y -->
	<!-- end banner -->

	<!-- start danpin -->
		<div class="danpin center">
			
			<div class="biaoti center">小米手机</div>
			<div class="main center">
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href="./xiangqing.html" target="_blank"><img src="./image/liebiao_xiaomi6.jpg" alt=""></a></div>
					<div class="pinpai"><a href="./xiangqing.html" target="_blank">小米6</a></div>
					<div class="youhui">5.16早10点开售</div>
					<div class="jiage">2499.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_xiaomi5c.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">小米手机5c</a></div>
					<div class="youhui">搭载澎湃S1 八核高性能处理器</div>
					<div class="jiage">1499.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_xiaomint2.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">小米Note 2</a></div>
					<div class="youhui">5月9日-20日 小米Note 2 享花呗12期分期免息</div>
					<div class="jiage">2799.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_xiaomimix.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">小米MIX</a></div>
					<div class="youhui">5月9日-20日小米MIX 享花呗12期分期免息</div>
					<div class="jiage">3499.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_xiaomi5s.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">小米5s</a></div>
					<div class="youhui">“暗夜之眼”超感光相机 / 无孔式超声波</div>
					<div class="jiage">1999.00元</div>
				</div>

				<div class="clear"></div>
			</div>
			<div class="main center mb20">
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_xiaomi5.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">小米手机5</a></div>
					<div class="youhui">骁龙820处理器 / UFS 2.0 闪存</div>
					<div class="jiage">1799.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_hongmin4.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">红米Note 4</a></div>
					<div class="youhui">十核旗舰处理器 / 全金属一体化机身 </div>
					<div class="jiage">1399.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/pinpai3.png" alt=""></a></div>
					<div class="pinpai"><a href="">小米手机5 64GB</a></div>
					<div class="youhui">5月9日-10日，下单立减100元</div>
					<div class="jiage">1799元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_hongmin42.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">红米4</a></div>
					<div class="youhui">2.5D 玻璃，金属一体化机身</div>
					<div class="jiage">999.00元</div>
				</div>
				<div class="mingxing fl mb20" style="border:2px solid #fff;width:230px;cursor:pointer;" onmouseout="this.style.border='2px solid #fff'" onmousemove="this.style.border='2px solid red'">
					<div class="sub_mingxing"><a href=""><img src="./image/liebiao_hongmin4x.jpg" alt=""></a></div>
					<div class="pinpai"><a href="">红米Note 4X 全网通版</a></div>
					<div class="youhui">多彩金属 / 4100mAh 超长续航</div>
					<div class="jiage">1299.00元</div>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		

		<footer class="mt20 center">			
			<div class="mt20">小米商城|MIUI|米聊|多看书城|小米路由器|视频电话|小米天猫店|小米淘宝直营店|小米网盟|小米移动|隐私政策|Select Region</div>
			<div>©mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2014]0059-0009号</div> 
			<div>违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试</div>

		</footer>

	<!-- end danpin -->


	</body>
</html>

mall/stores/templates/stores/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改店铺信息</title>
</head>
<body>
    <h1>修改店铺信息</h1>
    <form action="{% url 'stores:update' store.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        店铺名称：<input type="text" name="name" value="{{store.name}}"> <br>
        店铺封面：<input type="file" name="cover" id="cover"> <br>
        店铺介绍 <textarea name="intro" id="intro" cols="30" rows="10">{{store.intro}}</textarea> <br>
        <input type="submit" value="保存修改">
    </form>
</body>
</html>