mall/mall/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("user.urls", namespace='user')),
	url(r"^goods/", include("goods.urls", namespace="goods")),
	url(r"^stores/", include("stores.urls", namespace="stores")),
	url(r"^$", include("common.urls", namespace="common")),
]

mall/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^login/$", views.user_login, name="login"),
    url(r"^register/$", views.register, name="register"),
    url(r"^user_logout/$", views.user_logout, name="user_logout"),

]

mall/user/models.py
from django.db import models
# from datetime import datetime
# 引入django 中的用户表
from django.contrib.auth.models import User
# Create your models here.


class UserInfo(models.Model):
    # 编号
    id = models.AutoField(primary_key=True)
    # 用户昵称
    nickname = models.CharField(max_length=255, unique=True, verbose_name="用户昵称")
    # 用户年龄
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    # 用户性别
    gender = models.CharField(max_length=10, default='男', verbose_name="用户性别")
    # 用户头像
    header = models.ImageField(upload_to="static/img/tou_img", default="static/img/tou_img/default.png", verbose_name="用户头像")
    # 联系电话
    phone = models.CharField(max_length=50, default='11111111111', verbose_name="联系方式")

    # 一对一关联用户表
    user = models.OneToOneField(User, on_delete=models.CASCADE)

mall/user/views.py
from django.shortcuts import render
# 引入数据库用户名表
from django.contrib.auth.models import User
# django内置的登陆推出方法
from django.contrib.auth import authenticate,logout,login
# 引入models模块
from . import models


# 用户登陆
def user_login(request):
    if request.method == "GET":
        return render(request, "user/login.html", {"msg": "请登录"})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                # 将验证通过的用户信息保存到reques，
                login(request, user)
                return render(request, "user/userInfo.html", {"user": user})
            else:
                return render(request, "user/login.html", {"error_code": 2, "msg": "你的账号已经被锁定，请联系管理员"})
        else:
            return render(request, "user/login.html", {"error_code": 3, "msg": "用户名称或者密码错误，请重新登录"})



# 用户注册
def register(request):
    if request.method == "GET":
        return render(request, "user/register.html", {"msg": "请认真填写如下选项"})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()
        nickname = request.POST["nickname"]
        confirmpwd = request.POST["confirmpwd"].strip()
        # phone = request.POST["phone"]


        # 两次密码判断
        if password != confirmpwd:
            return render(request, 'user/register.html', {"error_code": 1, "msg": "两次密码不一致，请重新输入"})

        # 验证码判断

        # 判断用户名是否相可用
        if len(username) < 1:
            return render(request, "user/register.html", {"msg": "用户名不能为空！！！"})
        if len(password) < 6:
            return render(request, "user/register.html", {"msg": "密码长度不能小于6位！！！"})

        try:
            User.objects.get(username=username)
            return render(request, 'user/register.html', {"error_code": 2, "msg": "用户名已存在，请重新输入"})
        except:
            try:
                models.UserInfo.object.get(nickname=nickname)
                return render(request, "user/register.html", {"error_code": 3, "msg": "该用户昵称已经存在，请重新输入"})
            except:
                # 保存用户信息
                user = User.objects.create_user(username=username, password=password,)
                userInfo = models.UserInfo(nickname=nickname, user=user)

                user.save()
                userInfo.save()

                return render(request, "user/login.html", {"error_code": 1, "msg": "用户注册成功，请登录"})



# 用户退出
def user_logout(request):
    logout(request)
    return render(request, "user/login.html", {"error_code": 4, "msg": "退出成功，请重新登录"})

mall/user/templates/user/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <!--<meta name="author" content="order by dede58.com"/>-->
		<title>会员登录</title>
		<link rel="stylesheet" type="text/css" href="/static/css/login.css">

	</head>
	<body>
		<!--&lt;!&ndash; login &ndash;&gt;-->
		<!--<div class="top center">-->
			<!--<div class="logo center">-->
				<!--<a href="./index.html" target="_blank"><img src="/static/image/mistore_logo.png" alt=""></a>-->
			<!--</div>-->
		<!--</div>-->
		<!--<form  method="post" action="{% url 'user:login' %}" class="form center">-->
			<!--{% csrf_token %}-->
		<!--<div class="login">-->
			<!--<div class="login_center">-->
				<!--<div class="login_top">-->
					<!--<div class="left fl">会员登录</div>-->
					<!--<div class="right fr">您还不是我们的会员？<a href="register.html" target="_self">立即注册</a></div>-->
					<!--<div class="clear"></div>-->
					<!--<div class="xian center"></div>-->
				<!--</div>-->
				<!--<div class="login_main center">-->
					<!--<div class="username">用户名:&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入你的用户名"/></div>-->
					<!--<div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/></div>-->
					<!--&lt;!&ndash;<div class="username">&ndash;&gt;-->
						<!--&lt;!&ndash;<div class="left fl">验证码:&nbsp;<input class="yanzhengma" type="text" name="username" placeholder="请输入验证码"/></div>&ndash;&gt;-->
						<!--&lt;!&ndash;<div class="right fl"><img src="./image/yanzhengma.jpg"></div>&ndash;&gt;-->
						<!--&lt;!&ndash;<div class="clear"></div>&ndash;&gt;-->
					<!--&lt;!&ndash;</div>&ndash;&gt;-->
				<!--</div>-->
				<!--<div class="login_submit">-->
					<!--<input class="submit" type="submit" name="submit" value="立即登录" >-->
				<!--</div>-->
				<!---->
			<!--</div>-->
		<!--</div>-->
		<!--</form>-->
		<!--<footer>-->
			<!--<div class="copyright">简体 | 繁体 | English | 常见问题</div>-->
			<!--<div class="copyright">小米公司版权所有-京ICP备10046444-<img src="./image/ghs.png" alt="">京公网安备11010802020134号-京ICP证110507号</div>-->

		<!--</footer>-->

	    <h1>用户登陆</h1>
		{{  msg   }}
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        用户名：<input type="text" name="username"><br>
        密&nbsp;码：<input type="password" name="password"><br>
        <input type="submit" value="用户登陆">
    </form>


	</body>
</html>

mall/user/templates/user/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>会员登陆</title>
    <link rel="stylesheet" href="/user/static/login.css">
    <link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css ">
    <script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>


    <!--<link rel="stylesheet" href="/static/css/login.css">-->
</head>
<body>
    <!--<div class="top center">-->
			<!--<div class="logo center">-->
				<!--&lt;!&ndash;<a href="./index.html" target="_blank"><img src="./image/mistore_logo.png" alt=""></a>&ndash;&gt;-->
				<!--<a href="./index.html" target="_blank"><img src="static/img/mistore_logo.png" alt=""></a>-->
			<!--</div>-->
		<!--</div>-->
		<!--<form  method="post" action="./login.php" class="form center">-->
		<!--<div class="login">-->
			<!--<div class="login_center">-->
				<!--<div class="login_top">-->
					<!--<div class="left fl">会员登录</div>-->
					<!--<div class="right fr">您还不是我们的会员？<a href="./register.html" target="_self">立即注册</a></div>-->
					<!--<div class="clear"></div>-->
					<!--<div class="xian center"></div>-->
				<!--</div>-->
				<!--<div class="login_main center">-->
					<!--<div class="username">用户名:&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入你的用户名"/></div>-->
					<!--<div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/></div>-->
					<!--<div class="username">-->
						<!--<div class="left fl">验证码:&nbsp;<input class="yanzhengma" type="text" name="username" placeholder="请输入验证码"/></div>-->
						<!--<div class="right fl"><img src="./image/yanzhengma.jpg"></div>-->
						<!--<div class="clear"></div>-->
					<!--</div>-->
				<!--</div>-->
				<!--<div class="login_submit">-->
					<!--<input class="submit" type="submit" name="submit" value="立即登录" >-->
				<!--</div>-->

			<!--</div>-->
		<!--</div>-->
		<!--</form>-->
		<!--<footer>-->
			<!--<div class="copyright">简体 | 繁体 | English | 常见问题</div>-->
			<!--<div class="copyright">小米公司版权所有-京ICP备10046444-<img src="./image/ghs.png" alt="">京公网安备11010802020134号-京ICP证110507号</div>-->

		<!--</footer>-->


<div class="container">

    <div class='row'>
        <img src="/static/img/mistore_logo.png" alt="">
    </div>
    <div ></div>
    <div class="row">
        <div class="col-md-6 col-md-offset-4">
            <form class="form-horizontal" action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">账号：</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="username" name="username"  placeholder="请输入账号">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">密码：</label>
                    <div class="col-sm-6">
                        <input type="password" class="form-control" id="password" name="password"  placeholder="请输入密码">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> 记住密码
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">登录</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>

    <!--<h1>用户登陆</h1>-->
    <!--<form action="{% url 'user:login' %}" method="post">-->
        <!--{% csrf_token %}-->
        <!--用户名：<input type="text" name="username"><br>-->
        <!--密&nbsp;码：<input type="password" name="password"><br>-->
        <!--<input type="submit" value="用户登陆">-->
    <!--</form>-->
</body>
</html>

mall/user/templates/user/register.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>会员注册</title>-->
<!--</head>-->
<!--<body>-->
     <!--<h1>用户注册</h1>-->
    <!--<form action="{% url 'user:register' %}" method="post">-->
        <!--{% csrf_token %}-->
        <!--用户名称：<input type="text" name="username"><br>-->
        <!--用户昵称：<input type="text" name="nickname"><br>-->
        <!--用户密码：<input type="password" name="password"><br>-->
        <!--确认密码：<input type="password" name="confirmpwd"><br>-->
        <!--<input type="submit" value="用户注册">-->
    <!--</form>-->
<!--</body>-->
<!--</html>-->

<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <!--<meta name="author" content="order by dede58.com"/>-->
		<title>用户注册</title>
		<link rel="stylesheet" type="text/css" href="/static/css/login.css">
	</head>
	<body>
		<form  method="post" action="{% url 'user:register' %}">
             {% csrf_token %}
		<div class="regist">
			<div class="regist_center">
				<div class="regist_top">
					<div class="left fl">会员注册</div>
					<div class="right fr"><a href="./index.html" target="_self">小米商城</a></div>
					<div class="clear"></div>
					<div class="xian center"></div>
				</div>
				<div class="regist_main center">
					<div class="username">用&nbsp;&nbsp;户&nbsp;&nbsp;名:&nbsp;&nbsp;<input class="shurukuang" type="text" name="username" placeholder="请输入你的用户名"/><span>请不要输入汉字</span></div>
					<div class="username">用户昵称:&nbsp;&nbsp;<input class="shurukuang" type="text" name="nickname" placeholder="请输入你的用户名"/><span>昵称为汉字</span></div>
					<div class="username">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码:&nbsp;&nbsp;<input class="shurukuang" type="password" name="password" placeholder="请输入你的密码"/><span>请输入6位以上字符</span></div>

					<div class="username">确认密码:&nbsp;&nbsp;<input class="shurukuang" type="password" name="confirmpwd" placeholder="请确认你的密码"/><span>两次密码要输入一致哦</span></div>
					<div class="username">手&nbsp;&nbsp;机&nbsp;&nbsp;号:&nbsp;&nbsp;<input class="shurukuang" type="text" name="phone" placeholder="请填写正确的手机号"/><span>填写下手机号吧，方便我们联系您！</span></div>
					<!--<div class="username">-->
						<!--<div class="left fl">验&nbsp;&nbsp;证&nbsp;&nbsp;码:&nbsp;&nbsp;<input class="yanzhengma" type="text" name="username" placeholder="请输入验证码"/></div>-->
						<!--<div class="right fl"><img src="/user/static/image/yanzhengma.jpg"></div>-->
						<!--<div class="clear"></div>-->
					<!--</div>-->
				</div>
				<div class="regist_submit">
					<input class="submit" type="submit" name="submit" value="立即注册" >
				</div>
			</div>
		</div>
		</form>
	</body>
</html>

mall/user/templates/user/userInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户详情</title>
</head>
<body>
    <table>
        <tr>
            <td>用户头像</td>
            <td><img src="/{{user.userinfo.header}}" alt="1"></td>
        </tr>
        <tr>
            <td>用户名称</td>
            <td>{{user.username}}</td>
        </tr>
        <tr>
            <td>用户昵称</td>
            <td>{{user.userinfo.nickname}}</td>
        </tr>
        <tr>
            <td>联系电话</td>
            <td>{{user.userinfo.phone}}</td>
        </tr>
    </table>
</body>
</html>